name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
  ref:
    description: 'The repository ref <owner>/<repo>'
    required: true
    default: 'Test/test'
# outputs:
#   time: # output will be available to future steps
#     description: 'The message to output'
runs:
  using: 'node12'
  main: '../dist/index.js'
